# Generated by Django 3.2.12 on 2025-04-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0007_add_salarys'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_booking',
            name='Room_Number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
